import { plural } from "./brief";
import {
  camel,
  displayField,
  enabledScreens,
  pascal,
  primaryOf,
  tsTypeFor,
  type AppSpec,
  type EntitySpec,
  type Field,
  type ScreenSpec,
} from "./app";
import { themeToCss } from "./theme";
import { MILESTONES, tasksIn } from "./tasks";
import type { DocPage } from "./docs";
import type { Brief, Finding, ScaffoldFile, Task } from "./types";

function lines(...parts: (string | false | null | undefined)[]) {
  return parts.filter((p): p is string => typeof p === "string").join("\n");
}

/** `/shoots/[id]` -> `app/shoots/[id]/page.tsx` */
function pathFor(route: string): string {
  const clean = route.replace(/^\/+|\/+$/g, "");
  return clean ? `app/${clean}/page.tsx` : "app/page.tsx";
}

function labelFor(field: Field): string {
  return field.name
    .replace(/Id$/, "")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/^./, (c) => c.toUpperCase());
}

function statusValues(entity: EntitySpec): string[] {
  return /deposit|payment|invoice|order|fee|charge/i.test(entity.name)
    ? ["pending", "paid", "failed", "refunded"]
    : ["draft", "active", "archived"];
}

// ---------------------------------------------------------------------------
// lib/types.ts
// ---------------------------------------------------------------------------

function typesFile(app: AppSpec): ScaffoldFile {
  const blocks: string[] = [];
  const unions: string[] = [];

  for (const entity of app.entities) {
    if (entity.fields.some((f) => f.type === "status")) {
      unions.push(
        `export type ${pascal(entity.name)}Status = ${statusValues(entity)
          .map((v) => `"${v}"`)
          .join(" | ")};`
      );
    }
    blocks.push(
      lines(
        `export interface ${pascal(entity.name)} {`,
        ...entity.fields.map(
          (field) =>
            `  ${field.name}${field.required ? "" : "?"}: ${tsTypeFor(field, entity.name)};`
        ),
        `}`
      )
    );
  }

  return {
    path: "lib/types.ts",
    language: "ts",
    because:
      "Exactly the fields you set in Screens. Change one there and this changes with it — the preview and this file read the same list, so they can't disagree.",
    contents: lines(
      `// Generated by Loom.`,
      `// What the app keeps: ${app.entities.map((e) => e.name).join(", ")}.`,
      ``,
      unions.join("\n"),
      unions.length ? `` : null,
      blocks.join("\n\n"),
      ``
    ),
  };
}

// ---------------------------------------------------------------------------
// lib/data.ts
// ---------------------------------------------------------------------------

function dataFile(app: AppSpec, entities: EntitySpec[]): ScaffoldFile {
  const parts: string[] = [
    `// Generated by Loom. Every screen reads and writes through this module.`,
    `// Replace the in-memory maps with your database; the screens don't change.`,
    ``,
    `import type { ${entities.map((e) => pascal(e.name)).join(", ")} } from "./types";`,
    ``,
  ];

  for (const entity of entities) {
    const Type = pascal(entity.name);
    const many = pascal(plural(entity.name));
    const store = camel(plural(entity.name));

    parts.push(
      lines(
        `const ${store} = new Map<string, ${Type}>();`,
        ``,
        `export async function list${many}(): Promise<${Type}[]> {`,
        `  return [...${store}.values()].sort((a, b) => b.createdAt - a.createdAt);`,
        `}`,
        ``,
        `export async function get${Type}(id: string): Promise<${Type} | null> {`,
        `  return ${store}.get(id) ?? null;`,
        `}`,
        ``,
        `export async function create${Type}(`,
        `  input: Omit<${Type}, "id" | "createdAt">`,
        `): Promise<${Type}> {`,
        `  const record: ${Type} = {`,
        `    ...input,`,
        `    id: crypto.randomUUID(),`,
        `    createdAt: Date.now(),`,
        `  };`,
        `  ${store}.set(record.id, record);`,
        `  return record;`,
        `}`,
        ``,
        `// TODO(loom): deletion is undefined — refuse while something still points`,
        `// at it, keep a marker where it was, or remove everything with it? Until`,
        `// that's decided this throws rather than guessing. See docs/04.`,
        `export async function remove${Type}(): Promise<never> {`,
        `  throw new Error("Deletion not decided yet — see docs/04-what-we-store.md");`,
        `}`,
        ``
      )
    );
  }

  return {
    path: "lib/data.ts",
    language: "ts",
    because:
      "One module in front of storage, so swapping in a real database is a one-file change. Deleting deliberately throws — that decision hasn't been made, and guessing at it is how data goes missing.",
    contents: parts.join("\n"),
  };
}

// ---------------------------------------------------------------------------
// Screens
// ---------------------------------------------------------------------------

function listPage(screen: ScreenSpec, entity: EntitySpec): ScaffoldFile {
  const Type = pascal(entity.name);
  const many = pascal(plural(entity.name));
  const store = camel(plural(entity.name));
  const label = plural(entity.name);
  const one = entity.name.toLowerCase();
  const shown = displayField(entity)?.name ?? "id";

  return {
    path: pathFor(screen.route),
    language: "tsx",
    because:
      "The empty state is written before the populated one, because it's what every single person sees on their first visit.",
    contents: lines(
      `import Link from "next/link";`,
      ``,
      `import { list${many} } from "@/lib/data";`,
      `import type { ${Type} } from "@/lib/types";`,
      ``,
      `export default async function ${many}Page() {`,
      `  const ${store} = await list${many}();`,
      ``,
      `  // The most-seen version of the most-seen screen, written first on purpose.`,
      `  if (${store}.length === 0) {`,
      `    return (`,
      `      <main className="mx-auto max-w-2xl p-8">`,
      `        <h1 className="text-xl font-semibold tracking-tight">${label}</h1>`,
      `        <div className="mt-8 rounded-xl border border-dashed p-10 text-center">`,
      `          <p className="text-sm font-medium">No ${label.toLowerCase()} yet</p>`,
      `          <p className="mt-2 text-sm text-muted-foreground">`,
      `            {/* TODO(loom): this copy is the onboarding. Say what a ${one} is`,
      `                for, and what happens once they add the first one. */}`,
      `            Add your first ${one} to get started.`,
      `          </p>`,
      `          <Link`,
      `            href="${screen.route}/new"`,
      `            className="mt-4 inline-block rounded-md bg-primary px-3 py-1.5 text-sm text-primary-foreground"`,
      `          >`,
      `            Add a ${one}`,
      `          </Link>`,
      `        </div>`,
      `      </main>`,
      `    );`,
      `  }`,
      ``,
      `  return (`,
      `    <main className="mx-auto max-w-2xl p-8">`,
      `      <div className="flex items-center justify-between">`,
      `        <h1 className="text-xl font-semibold tracking-tight">${label}</h1>`,
      `        <Link href="${screen.route}/new" className="text-sm underline underline-offset-4">`,
      `          New ${one}`,
      `        </Link>`,
      `      </div>`,
      ``,
      `      {/* TODO(loom): past a few hundred records this needs search, sort and`,
      `          paging. Those change the screen rather than decorate it. */}`,
      `      <ul className="mt-6 divide-y rounded-xl border">`,
      `        {${store}.map((${camel(entity.name)}: ${Type}) => (`,
      `          <li key={${camel(entity.name)}.id}>`,
      `            <Link`,
      `              href={\`${screen.route}/\${${camel(entity.name)}.id}\`}`,
      `              className="block px-4 py-3 text-sm hover:bg-accent"`,
      `            >`,
      `              {${camel(entity.name)}.${shown}}`,
      `            </Link>`,
      `          </li>`,
      `        ))}`,
      `      </ul>`,
      `    </main>`,
      `  );`,
      `}`,
      ``
    ),
  };
}

function detailPage(screen: ScreenSpec, entity: EntitySpec): ScaffoldFile {
  const Type = pascal(entity.name);
  const record = camel(entity.name);
  const shown = displayField(entity)?.name ?? "id";
  const rest = entity.fields.filter((f) => f.name !== "id" && f.name !== shown);

  return {
    path: pathFor(screen.route),
    language: "tsx",
    because:
      "Stops at the permission question rather than guessing. Right now \"not found\" and \"you can't see this\" are the same answer, and which one you show is a decision.",
    contents: lines(
      `import { notFound } from "next/navigation";`,
      ``,
      `import { get${Type} } from "@/lib/data";`,
      ``,
      `// params is a promise in this version of Next.js.`,
      `export default async function ${Type}Page({`,
      `  params,`,
      `}: {`,
      `  params: Promise<{ id: string }>;`,
      `}) {`,
      `  const { id } = await params;`,
      `  const ${record} = await get${Type}(id);`,
      ``,
      `  // TODO(loom): "doesn't exist" and "isn't yours" are the same response`,
      `  // here. Collapsing them hides what exists, which may be what you want.`,
      `  // Decide on purpose, then delete this comment.`,
      `  if (!${record}) notFound();`,
      ``,
      `  return (`,
      `    <main className="mx-auto max-w-2xl p-8">`,
      `      <h1 className="text-xl font-semibold tracking-tight">{${record}.${shown}}</h1>`,
      `      <dl className="mt-6 overflow-hidden rounded-xl border">`,
      ...rest.map((field) =>
        lines(
          `        <div className="flex justify-between gap-4 border-b px-4 py-3 last:border-0">`,
          `          <dt className="text-sm text-muted-foreground">${labelFor(field)}</dt>`,
          `          <dd className="text-sm font-medium">{String(${record}.${field.name} ?? "—")}</dd>`,
          `        </div>`
        )
      ),
      `      </dl>`,
      `    </main>`,
      `  );`,
      `}`,
      ``
    ),
  };
}

function createPage(
  screen: ScreenSpec,
  entity: EntitySpec,
  money: boolean
): ScaffoldFile {
  const Type = pascal(entity.name);
  const editable = entity.fields.filter(
    (f) => !f.system && f.type !== "link" && f.type !== "status"
  );
  const first = editable[0];

  return {
    path: pathFor(screen.route),
    language: "tsx",
    because: money
      ? "Carries the three situations that matter once money is involved: saving, declined, and connection-lost-mid-payment. Those are not the same thing and must not look the same."
      : "Carries the failure path, not just the happy one. Saving and failing are states, not afterthoughts.",
    contents: lines(
      `"use client";`,
      ``,
      `import * as React from "react";`,
      `import { useRouter } from "next/navigation";`,
      ``,
      money
        ? `type Status = "idle" | "saving" | "declined" | "unknown" | "failed";`
        : `type Status = "idle" | "saving" | "failed";`,
      ``,
      `export default function New${Type}Page() {`,
      `  const router = useRouter();`,
      first ? `  const [value, setValue] = React.useState("");` : null,
      `  const [status, setStatus] = React.useState<Status>("idle");`,
      ``,
      `  async function submit(event: React.FormEvent) {`,
      `    event.preventDefault();`,
      `    if (status === "saving") return; // stops a double tap saving twice`,
      `    setStatus("saving");`,
      ``,
      `    try {`,
      `      const res = await fetch("/api${screen.route.replace(/\/new$/, "")}", {`,
      `        method: "POST",`,
      `        headers: { "Content-Type": "application/json" },`,
      first
        ? `        body: JSON.stringify({ ${first.name}: value }),`
        : `        body: "{}",`,
      `      });`,
      money
        ? lines(
            `      // A payment can go through after we've lost the answer. Treat that`,
            `      // as unknown, never as failed — telling someone it failed when it`,
            `      // didn't is how you get charged twice.`,
            `      if (res.status === 402) return setStatus("declined");`
          )
        : null,
      `      if (!res.ok) return setStatus("failed");`,
      `      router.push("${screen.route.replace(/\/new$/, "")}");`,
      `    } catch {`,
      money ? `      setStatus("unknown");` : `      setStatus("failed");`,
      `    }`,
      `  }`,
      ``,
      `  return (`,
      `    <main className="mx-auto max-w-md p-8">`,
      `      <h1 className="text-xl font-semibold tracking-tight">${screen.name}</h1>`,
      ``,
      `      <form onSubmit={submit} className="mt-6 space-y-4">`,
      first
        ? lines(
            `        <label className="block text-sm font-medium" htmlFor="${first.name}">`,
            `          ${labelFor(first)}`,
            `        </label>`,
            `        <input`,
            `          id="${first.name}"`,
            `          value={value}`,
            `          onChange={(e) => setValue(e.target.value)}`,
            `          required`,
            `          className="w-full rounded-md border px-3 py-2 text-sm"`,
            `        />`
          )
        : null,
      ``,
      `        <button`,
      `          type="submit"`,
      `          disabled={status === "saving"}`,
      `          className="w-full rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50"`,
      `        >`,
      `          {status === "saving" ? "Saving…" : "Save"}`,
      `        </button>`,
      `      </form>`,
      ``,
      `      {/* TODO(loom): this wording is a guess. It should say whether trying`,
      `          again would help. */}`,
      `      {status === "failed" ? (`,
      `        <p className="mt-4 text-sm text-destructive">`,
      `          That didn&apos;t save. Nothing was lost — try again.`,
      `        </p>`,
      `      ) : null}`,
      money
        ? lines(
            `      {status === "declined" ? (`,
            `        <p className="mt-4 text-sm text-destructive">`,
            `          The payment was declined. Nothing has been charged.`,
            `        </p>`,
            `      ) : null}`,
            `      {status === "unknown" ? (`,
            `        <p className="mt-4 text-sm text-muted-foreground">`,
            `          We lost the connection while this was going through. Don&apos;t try`,
            `          again yet — check your email for a confirmation first.`,
            `        </p>`,
            `      ) : null}`
          )
        : null,
      `    </main>`,
      `  );`,
      `}`,
      ``
    ),
  };
}

function simplePage(screen: ScreenSpec): ScaffoldFile {
  return {
    path: pathFor(screen.route),
    language: "tsx",
    because: screen.custom
      ? "You added this screen yourself, so no review has looked at it. It's a stub until you say what it's for."
      : "A starting point. This screen's contents depend on decisions that haven't been made yet.",
    contents: lines(
      `export default function ${pascal(screen.name.replace(/[^a-zA-Z ]/g, "")) || "Screen"}Page() {`,
      `  return (`,
      `    <main className="mx-auto max-w-2xl p-8">`,
      `      <h1 className="text-xl font-semibold tracking-tight">${screen.name}</h1>`,
      `      {/* TODO(loom): ${screen.note}. */}`,
      `      <p className="mt-4 text-sm text-muted-foreground">`,
      `        Not built yet.`,
      `      </p>`,
      `    </main>`,
      `  );`,
      `}`,
      ``
    ),
  };
}

// ---------------------------------------------------------------------------
// Plan + config
// ---------------------------------------------------------------------------

function buildPlan(brief: Brief, tasks: Task[]): ScaffoldFile {
  const out: string[] = [
    `# Build plan — ${brief.product || "Untitled"}`,
    ``,
    `**For:** ${brief.actorPlural}`,
    `**The one thing it must do:** ${brief.job || "—"}`,
    `**Tasks:** ${tasks.length}`,
    ``,
    `Generated by Loom. Ticked boxes are what you've marked done in the app.`,
    `Plain-language background for all of this is in \`docs/\`.`,
    ``,
  ];

  for (const milestone of MILESTONES) {
    const group = tasksIn(tasks, milestone.id);
    if (group.length === 0) continue;
    out.push(`## ${milestone.title} (${group.length})`, ``, milestone.blurb, ``);
    for (const task of group) {
      const flags = [task.size, task.from, task.severity].filter(Boolean);
      out.push(`- [ ] **${task.plain.what}** — \`${flags.join(" · ")}\``);
      out.push(`      ${task.plain.why}`);
      out.push(`      *Done when:* ${task.plain.done}`);
    }
    out.push(``);
  }

  out.push(
    `## Not in the first version`,
    ``,
    brief.outOfScope ||
      "Nothing has been ruled out. Worth naming three things before the first build meeting.",
    ``
  );

  return {
    path: "BUILD.md",
    language: "md",
    because:
      "The task list as a file, so it survives outside this browser and can sit in the repo next to the code.",
    contents: out.join("\n") + "\n",
  };
}

function componentsJson(): ScaffoldFile {
  return {
    path: "components.json",
    language: "json",
    because:
      "So `npx shadcn add` works in your project and anything you add picks up the theme automatically.",
    contents:
      JSON.stringify(
        {
          $schema: "https://ui.shadcn.com/schema.json",
          style: "new-york",
          rsc: true,
          tsx: true,
          tailwind: { config: "", css: "app/globals.css", baseColor: "slate", cssVariables: true, prefix: "" },
          iconLibrary: "lucide",
          aliases: {
            components: "@/components",
            utils: "@/lib/utils",
            ui: "@/components/ui",
            lib: "@/lib",
            hooks: "@/hooks",
          },
        },
        null,
        2
      ) + "\n",
  };
}

// ---------------------------------------------------------------------------

export interface ScaffoldInput {
  brief: Brief;
  app: AppSpec;
  findings: Finding[];
  tasks: Task[];
  docs: DocPage[];
}

/**
 * The starting codebase.
 *
 * Not a finished app — the parts that can actually be worked out from your
 * answers. Where a review found an open question, the code stops and says so
 * rather than picking for you.
 */
export function generateScaffold(input: ScaffoldInput): ScaffoldFile[] {
  const { brief, app, findings, tasks, docs } = input;

  const money =
    findings.some((f) => f.tags.includes("trust")) ||
    /pay|deposit|invoice|checkout|charge|billing/i.test(
      `${brief.job} ${brief.product}`
    );

  const screens = enabledScreens(app);
  const usedEntityIds = new Set(
    screens.map((s) => s.entityId).filter((id): id is string => !!id)
  );
  const dataEntities = app.entities.filter((e) => usedEntityIds.has(e.id));
  const primary = primaryOf(app);

  const files: ScaffoldFile[] = [
    buildPlan(brief, tasks),
    {
      path: "app/globals.css",
      language: "css",
      because:
        "Your design system, as the standard shadcn setup. Every colour, corner and typeface on every screen comes from this one file.",
      contents: themeToCss(app.theme),
    },
    componentsJson(),
    typesFile(app),
    dataFile(app, dataEntities.length ? dataEntities : [primary]),
  ];

  for (const screen of screens) {
    const entity = app.entities.find((e) => e.id === screen.entityId);
    if (screen.kind === "list" && entity) files.push(listPage(screen, entity));
    else if (screen.kind === "detail" && entity) files.push(detailPage(screen, entity));
    else if (screen.kind === "create" && entity)
      files.push(createPage(screen, entity, money));
    else files.push(simplePage(screen));
  }

  for (const doc of docs) {
    files.push({
      path: doc.path,
      language: "md",
      because: doc.summary,
      contents: doc.body,
    });
  }

  return files;
}
