import { plural, singular } from "./brief";
import { fieldsFor, primaryEntity, screenInventory } from "./screens";
import { MILESTONES, tasksIn } from "./tasks";
import type { Brief, Finding, ScaffoldFile, Task } from "./types";

function lines(...parts: (string | false | null | undefined)[]) {
  return parts.filter((p): p is string => typeof p === "string").join("\n");
}

function routeSlug(name: string) {
  return name
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "");
}

function pascal(name: string) {
  return singular(name)
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function camel(name: string) {
  const p = pascal(name);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

// ---------------------------------------------------------------------------
// lib/types.ts
// ---------------------------------------------------------------------------

function typesFile(brief: Brief): ScaffoldFile {
  const statusTypes = new Map<string, string[]>();
  const blocks: string[] = [];

  for (const entity of brief.entities) {
    const fields = fieldsFor(entity, brief);
    for (const [, type] of fields) {
      if (!type.endsWith("Status")) continue;
      if (type === "PaymentStatus") {
        statusTypes.set(type, ["pending", "paid", "failed", "refunded"]);
      } else {
        statusTypes.set(type, ["draft", "active", "archived"]);
      }
    }
    blocks.push(
      lines(
        `export interface ${pascal(entity)} {`,
        ...fields.map(([name, type]) => `  ${name}: ${type};`),
        `}`
      )
    );
  }

  return {
    path: "lib/types.ts",
    language: "ts",
    because:
      "Straight out of the data model review. The owner field on every non-identity record is there because that review flagged ownership as undecided.",
    contents: lines(
      `// Generated by Loom from the data model review.`,
      `// Entities named in the interview: ${brief.entities.join(", ")}.`,
      ``,
      ...[...statusTypes.entries()].map(
        ([name, values]) =>
          `export type ${name} = ${values.map((v) => `"${v}"`).join(" | ")};`
      ),
      statusTypes.size > 0 ? `` : null,
      blocks.join("\n\n"),
      ``
    ),
  };
}

// ---------------------------------------------------------------------------
// lib/data.ts
// ---------------------------------------------------------------------------

function dataFile(brief: Brief): ScaffoldFile {
  const entity = primaryEntity(brief);
  const Type = pascal(entity);
  const many = pascal(plural(entity));
  const store = camel(plural(entity));

  return {
    path: "lib/data.ts",
    language: "ts",
    because:
      "One module in front of storage, so swapping the in-memory maps for a database is a one-file change. Deletion deliberately throws — the data model review found that decision hadn't been made.",
    contents: lines(
      `// Generated by Loom. Every screen reads and writes through this module.`,
      `// Replace the in-memory maps with your database; the screens don't change.`,
      ``,
      `import type { ${Type} } from "./types";`,
      ``,
      `const ${store} = new Map<string, ${Type}>();`,
      ``,
      `export async function list${many}(): Promise<${Type}[]> {`,
      `  return [...${store}.values()].sort((a, b) => b.createdAt - a.createdAt);`,
      `}`,
      ``,
      `export async function get${Type}(id: string): Promise<${Type} | null> {`,
      `  return ${store}.get(id) ?? null;`,
      `}`,
      ``,
      `export async function create${Type}(`,
      `  input: Omit<${Type}, "id" | "createdAt">`,
      `): Promise<${Type}> {`,
      `  const record: ${Type} = {`,
      `    ...input,`,
      `    id: crypto.randomUUID(),`,
      `    createdAt: Date.now(),`,
      `  };`,
      `  ${store}.set(record.id, record);`,
      `  return record;`,
      `}`,
      ``,
      `// TODO(loom): deletion is undefined — block while referenced, soft-delete`,
      `// and show a tombstone, or cascade? Until that's decided this throws`,
      `// rather than guessing. See data_model.md.`,
      `export async function remove${Type}(): Promise<never> {`,
      `  throw new Error("Deletion semantics undecided — see data_model.md");`,
      `}`,
      ``
    ),
  };
}

// ---------------------------------------------------------------------------
// Screens
// ---------------------------------------------------------------------------

function listPage(brief: Brief): ScaffoldFile {
  const entity = primaryEntity(brief);
  const Type = pascal(entity);
  const many = pascal(plural(entity));
  const slug = routeSlug(plural(entity));
  const label = plural(entity);
  const one = entity.toLowerCase();

  return {
    path: `app/${slug}/page.tsx`,
    language: "tsx",
    because:
      "The empty state is written before the populated one, because the edge case review found this list is empty on day one for every single user.",
    contents: lines(
      `import Link from "next/link";`,
      ``,
      `import { list${many} } from "@/lib/data";`,
      `import type { ${Type} } from "@/lib/types";`,
      ``,
      `export default async function ${many}Page() {`,
      `  const ${camel(plural(entity))} = await list${many}();`,
      ``,
      `  // The most-seen version of the most-seen screen. Written first on`,
      `  // purpose — see edge_cases.md.`,
      `  if (${camel(plural(entity))}.length === 0) {`,
      `    return (`,
      `      <main className="mx-auto max-w-2xl p-8">`,
      `        <h1 className="text-2xl font-semibold tracking-tight">${label}</h1>`,
      `        <div className="mt-8 rounded-xl border border-dashed p-10 text-center">`,
      `          <p className="text-sm text-neutral-500">`,
      `            {/* TODO(loom): this copy is the onboarding. Say what a ${one} is`,
      `                for, and what happens after they add the first one. */}`,
      `            No ${label.toLowerCase()} yet.`,
      `          </p>`,
      `          <Link`,
      `            href="/${slug}/new"`,
      `            className="mt-4 inline-block text-sm underline underline-offset-4"`,
      `          >`,
      `            Add the first one`,
      `          </Link>`,
      `        </div>`,
      `      </main>`,
      `    );`,
      `  }`,
      ``,
      `  return (`,
      `    <main className="mx-auto max-w-2xl p-8">`,
      `      <div className="flex items-center justify-between">`,
      `        <h1 className="text-2xl font-semibold tracking-tight">${label}</h1>`,
      `        <Link href="/${slug}/new" className="text-sm underline underline-offset-4">`,
      `          New ${one}`,
      `        </Link>`,
      `      </div>`,
      ``,
      `      {/* TODO(loom): scale_risk.md — at a few hundred records this needs`,
      `          search, sort and pagination. Those change the screen, not decorate it. */}`,
      `      <ul className="mt-6 divide-y rounded-xl border">`,
      `        {${camel(plural(entity))}.map((${camel(entity)}: ${Type}) => (`,
      `          <li key={${camel(entity)}.id}>`,
      `            <Link`,
      `              href={\`/${slug}/\${${camel(entity)}.id}\`}`,
      `              className="block px-4 py-3 text-sm hover:bg-neutral-50"`,
      `            >`,
      `              {${camel(entity)}.${fieldsFor(entity, brief).some(([n]) => n === "name") ? "name" : "title"}}`,
      `            </Link>`,
      `          </li>`,
      `        ))}`,
      `      </ul>`,
      `    </main>`,
      `  );`,
      `}`,
      ``
    ),
  };
}

function detailPage(brief: Brief): ScaffoldFile {
  const entity = primaryEntity(brief);
  const Type = pascal(entity);
  const slug = routeSlug(plural(entity));

  return {
    path: `app/${slug}/[id]/page.tsx`,
    language: "tsx",
    because:
      "Stops at the permission question rather than guessing. The edge case review pointed out that permission-denied is currently indistinguishable from not-found, and that's a decision worth making on purpose.",
    contents: lines(
      `import { notFound } from "next/navigation";`,
      ``,
      `import { get${Type} } from "@/lib/data";`,
      ``,
      `// params is a promise in this version of Next.js.`,
      `export default async function ${Type}Page({`,
      `  params,`,
      `}: {`,
      `  params: Promise<{ id: string }>;`,
      `}) {`,
      `  const { id } = await params;`,
      `  const ${camel(entity)} = await get${Type}(id);`,
      ``,
      `  // TODO(loom): edge_cases.md — "not found" and "you can't see this" are`,
      `  // currently the same response. Collapsing them hides what exists, which`,
      `  // may be what you want. Decide, then delete this comment.`,
      `  if (!${camel(entity)}) notFound();`,
      ``,
      `  return (`,
      `    <main className="mx-auto max-w-2xl p-8">`,
      `      <h1 className="text-2xl font-semibold tracking-tight">`,
      `        {${camel(entity)}.${fieldsFor(entity, brief).some(([n]) => n === "name") ? "name" : "title"}}`,
      `      </h1>`,
      `      <dl className="mt-6 space-y-2 text-sm text-neutral-600">`,
      ...fieldsFor(entity, brief)
        .filter(([n]) => n !== "id" && n !== "name" && n !== "title")
        .map((field) =>
          lines(
            `        <div className="flex gap-2">`,
            `          <dt className="font-medium">${field[0]}</dt>`,
            `          <dd>{String(${camel(entity)}.${field[0]})}</dd>`,
            `        </div>`
          )
        ),
      `      </dl>`,
      `    </main>`,
      `  );`,
      `}`,
      ``
    ),
  };
}

function createPage(brief: Brief, money: boolean): ScaffoldFile {
  const entity = primaryEntity(brief);
  const Type = pascal(entity);
  const slug = routeSlug(plural(entity));
  const field = fieldsFor(entity, brief).some(([n]) => n === "name")
    ? "name"
    : "title";

  return {
    path: `app/${slug}/new/page.tsx`,
    language: "tsx",
    because: money
      ? "Carries the three states the flow review demanded once money is in the primary flow: submitting, failed-retryable, and failed-terminal. The happy path is the easy third of this screen."
      : "Carries the failure path the flow review found missing. Submitting and error are states, not afterthoughts.",
    contents: lines(
      `"use client";`,
      ``,
      `import * as React from "react";`,
      `import { useRouter } from "next/navigation";`,
      ``,
      `// flows.md: the happy path was the only one specified. These are the rest.`,
      money
        ? `type Status = "idle" | "submitting" | "pending" | "retryable" | "failed";`
        : `type Status = "idle" | "submitting" | "failed";`,
      ``,
      `export default function New${Type}Page() {`,
      `  const router = useRouter();`,
      `  const [${field}, set${pascal(field)}] = React.useState("");`,
      `  const [status, setStatus] = React.useState<Status>("idle");`,
      ``,
      `  async function submit(event: React.FormEvent) {`,
      `    event.preventDefault();`,
      `    if (status === "submitting") return; // duplicate submit — flows.md`,
      `    setStatus("submitting");`,
      ``,
      `    try {`,
      `      const res = await fetch("/api/${slug}", {`,
      `        method: "POST",`,
      `        headers: { "Content-Type": "application/json" },`,
      `        body: JSON.stringify({ ${field} }),`,
      `      });`,
      money
        ? lines(
            `      // TODO(loom): a charge can succeed after the response is lost.`,
            `      // Treat a timeout as "pending", never as "failed" — see flows.md.`,
            `      if (res.status === 402) return setStatus("retryable");`
          )
        : null,
      `      if (!res.ok) return setStatus("failed");`,
      `      router.push("/${slug}");`,
      `    } catch {`,
      money ? `      setStatus("pending");` : `      setStatus("failed");`,
      `    }`,
      `  }`,
      ``,
      `  return (`,
      `    <main className="mx-auto max-w-md p-8">`,
      `      <h1 className="text-2xl font-semibold tracking-tight">New ${entity.toLowerCase()}</h1>`,
      ``,
      `      <form onSubmit={submit} className="mt-6 space-y-4">`,
      `        <input`,
      `          value={${field}}`,
      `          onChange={(e) => set${pascal(field)}(e.target.value)}`,
      `          required`,
      `          className="w-full rounded-lg border px-3 py-2 text-sm"`,
      `          placeholder="${field === "name" ? "Name" : "Title"}"`,
      `        />`,
      ``,
      `        <button`,
      `          type="submit"`,
      `          disabled={status === "submitting"}`,
      `          className="w-full rounded-lg bg-neutral-900 px-4 py-2 text-sm text-white disabled:opacity-50"`,
      `        >`,
      `          {status === "submitting" ? "Saving…" : "Save"}`,
      `        </button>`,
      `      </form>`,
      ``,
      `      {/* TODO(loom): edge_cases.md — this copy is unspecified. Distinguish`,
      `          "try again" from "this will never work". */}`,
      `      {status === "failed" ? (`,
      `        <p className="mt-4 text-sm text-red-600">That didn&apos;t save. Try again.</p>`,
      `      ) : null}`,
      money
        ? lines(
            `      {status === "retryable" ? (`,
            `        <p className="mt-4 text-sm text-amber-600">`,
            `          The payment was declined. Nothing was charged.`,
            `        </p>`,
            `      ) : null}`,
            `      {status === "pending" ? (`,
            `        <p className="mt-4 text-sm text-amber-600">`,
            `          We lost the connection while this was going through. Don&apos;t`,
            `          retry yet — check your email for confirmation first.`,
            `        </p>`,
            `      ) : null}`
          )
        : null,
      `    </main>`,
      `  );`,
      `}`,
      ``
    ),
  };
}

// ---------------------------------------------------------------------------
// BUILD.md
// ---------------------------------------------------------------------------

function buildPlan(brief: Brief, tasks: Task[]): ScaffoldFile {
  const out: string[] = [
    `# Build plan — ${brief.product || "Untitled"}`,
    ``,
    `**For:** ${brief.actorPlural}`,
    `**Primary job:** ${brief.job || "—"}`,
    `**Tasks:** ${tasks.length}`,
    ``,
    `Generated by Loom from the reviews in this project. Checked boxes are what`,
    `you've marked done in the app.`,
    ``,
  ];

  for (const milestone of MILESTONES) {
    const group = tasksIn(tasks, milestone.id);
    if (group.length === 0) continue;
    out.push(`## ${milestone.title} (${group.length})`, ``, milestone.blurb, ``);
    for (const task of group) {
      const flags: string[] = [task.size];
      if (task.from) flags.push(task.from);
      if (task.severity) flags.push(task.severity);
      out.push(`- [ ] **${task.title}** — \`${flags.join(" · ")}\``);
      out.push(`      ${task.detail}`);
    }
    out.push(``);
  }

  out.push(
    `## Not in v1`,
    ``,
    brief.outOfScope ||
      "Nothing was declared out of scope. Name three things before the first build meeting.",
    ``
  );

  return {
    path: "BUILD.md",
    language: "md",
    because:
      "The task list as a file, so it survives outside this browser and can go in the repo next to the code.",
    contents: out.join("\n") + "\n",
  };
}

// ---------------------------------------------------------------------------

/**
 * Generate a starting codebase.
 *
 * Not a finished app — the parts a review can actually determine: the types,
 * the storage seam, and the screens, each carrying the state the reviews found
 * missing. Where a review found an undecided question, the scaffold stops and
 * says so rather than picking for you.
 */
export function generateScaffold(
  brief: Brief,
  findings: Finding[],
  tasks: Task[]
): ScaffoldFile[] {
  const money = findings.some((f) => f.tags.includes("trust")) ||
    /pay|deposit|invoice|checkout|charge|billing/i.test(
      `${brief.job} ${brief.product}`
    );

  return [
    buildPlan(brief, tasks),
    typesFile(brief),
    dataFile(brief),
    listPage(brief),
    detailPage(brief),
    createPage(brief, money),
  ];
}

export { screenInventory };
